#!/usr/bin/env python3
"""Report Generator Module"""
import json
from datetime import datetime

class ReportGenerator:
    def __init__(self, input_file: str, output: str, logger):
        self.input_file = input_file
        self.output = output
        self.logger = logger

    def run(self):
        self.logger.info(f"[*] Generating report from {self.input_file}")
        try:
            with open(self.input_file) as f:
                data = json.load(f)
        except Exception as e:
            self.logger.error(f"Failed to read input: {e}")
            return

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ShadowEye OSINT Report</title>
    <style>
        body {{ font-family: monospace; background: #0d1117; color: #58a6ff; padding: 2em; }}
        h1 {{ color: #f85149; }} h2 {{ color: #3fb950; border-bottom: 1px solid #21262d; padding-bottom:.4em; }}
        pre {{ background: #161b22; padding: 1em; border-radius: 6px; overflow-x:auto; color:#e6edf3; }}
        .badge {{ display:inline-block; padding:2px 8px; border-radius:12px; font-size:.8em; background:#21262d; }}
        footer {{ margin-top:3em; color:#484f58; font-size:.8em; }}
    </style>
</head>
<body>
    <h1>👁️ ShadowEye OSINT Report</h1>
    <p><span class="badge">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</span>
       <span class="badge">Author: Shadow Core</span></p>
    <h2>📊 Results</h2>
    <pre>{json.dumps(data, indent=2)}</pre>
    <footer>Generated by ShadowEye OSINT Framework | For authorized use only</footer>
</body>
</html>"""

        with open(self.output, "w") as f:
            f.write(html)
        self.logger.success(f"Report saved to {self.output}")
